// WHY-NEW-FILE: tests/unit/map-policy-contract.test.ts
//   CLOSEST-EXISTING: tests/unit/weakest-link-surface-contract.test.ts
//   EXTENSION-COST: that file owns the *published morning's* wire contract --
//     the hourly projection, its validator and its readers -- which is republished
//     every build and whose inputs are model output. This file owns a *tracked
//     licence-and-attribution policy* whose input is the human-owned seed and
//     which changes only by pull request. Sharing one file would put a build
//     artefact's schema and a legal artefact's schema behind one name.
//   PARALLEL-RATIONALE: different lifecycle (per-build vs per-pull-request) and
//     an incompatible dependency set: nothing here may import the scoring or
//     publication surface, because a map credit must stay decidable when no
//     morning has been published at all.
//
// Driving port: `parseStaticMapPolicy()` and `decideStaticMapAssets()` in
// src/publish/static-map-policy.ts. Both are pure. The policy is read from disk
// by the caller, never by the module, so this contract stays testable without
// a filesystem.
//
// THE RULE THIS FILE EXISTS TO ENFORCE: a map may be drawn only where a citable
// source says both where the break is and which way it faces, AND that source
// can be credited visibly, in Spanish, on the page. Anything less is refused.
// Two launch spots (playa-la-barqueta, las-lajas) carry `orientation_source:
// null` in data/spots/pa-pacific.yaml: no source anywhere states their facing.
// They must lose their map rather than receive a plausible arrow.

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import fc from 'fast-check';
import { describe, it } from 'vitest';

import {
  decideStaticMapAssets,
  parseStaticMapPolicy,
  type StaticMapPolicy,
  type StaticMapSpotRecord,
} from '../../src/publish/static-map-policy';

const POLICY_PATH = fileURLToPath(new URL('../../data/maps/pa-pacific-map-policy.json', import.meta.url));
const LAUNCH_PATH = fileURLToPath(new URL('../../data/spots/pa-pacific-launch-v1.json', import.meta.url));

/** Same shapes the acceptance copy gate uses, so a leak fails here first. */
const CODE_LEAK = /\b(?:dir|size|wind|tide|weakest[_ -]?link|null|undefined|NaN|true|false|the|today|tomorrow)\b/i;
const EM_DASH = /[—]|--/;
const URL_SCHEME = /https?:\/\//iu;
const RAW_DEGREE = /\d\s*(?:°|deg\b|grados\b)/iu;

const trackedPolicy = parseStaticMapPolicy(JSON.parse(readFileSync(POLICY_PATH, 'utf8')));
const launchSpotIds = (JSON.parse(readFileSync(LAUNCH_PATH, 'utf8')) as { launch_spot_ids: readonly string[] })
  .launch_spot_ids;

const citableText = fc.stringMatching(/^[A-Za-zÁÉÍÓÚÑáéíóúñ][A-Za-zÁÉÍÓÚÑáéíóúñ .]{2,40}$/u);

/** A policy record generated by role: either fully citable, or missing exactly
 *  one of the two credits a map needs. Nothing in between exists. */
const spotRecord = fc.record({
  coordinate_attribution: fc.oneof(citableText, fc.constant('')),
  orientation_attribution: fc.oneof(citableText, fc.constant('')),
  coordinate_provenance: citableText,
  orientation_provenance: citableText,
});

function policyWith(spots: Readonly<Record<string, StaticMapSpotRecord>>): StaticMapPolicy {
  return { ...trackedPolicy, spots };
}

describe('the tracked static map policy', () => {
  it('decides every launch spot exactly once and credits every approved one', () => {
    const decisions = decideStaticMapAssets(trackedPolicy, launchSpotIds);

    assert.deepEqual(
      decisions.map((decision) => decision.spot_id).sort(),
      [...launchSpotIds].sort(),
      'the policy decided a different set of spots than the launch policy publishes',
    );

    for (const decision of decisions) {
      if (decision.kind !== 'approved') continue;
      const { caption, spot_id } = decision;
      assert.ok(caption.includes(decision.coordinate_attribution), `${spot_id} hides where its location came from`);
      assert.ok(caption.includes(decision.orientation_attribution), `${spot_id} hides where its facing came from`);
      assert.ok(!CODE_LEAK.test(caption), `${spot_id} leaks a code word into its credit: ${caption}`);
      assert.ok(!EM_DASH.test(caption), `${spot_id} uses a long dash in its credit: ${caption}`);
      assert.ok(!URL_SCHEME.test(caption), `${spot_id} prints a raw address in its credit: ${caption}`);
      assert.ok(!RAW_DEGREE.test(caption), `${spot_id} prints raw degrees in its credit: ${caption}`);
    }
  });

  it('refuses the two beaches no source can orient, rather than drawing a plausible arrow', () => {
    const refused = decideStaticMapAssets(trackedPolicy, launchSpotIds)
      .filter((decision) => decision.kind === 'refused')
      .map((decision) => `${decision.spot_id}:${decision.reason}`);

    assert.deepEqual(
      refused.sort(),
      ['las-lajas:orientation_attribution_missing', 'playa-la-barqueta:orientation_attribution_missing'],
      'the set of spots the policy refuses moved',
    );
  });
});

describe('the map decision, over any policy', () => {
  it('approves a spot only when both of its credits are citable', () => {
    fc.assert(
      fc.property(fc.dictionary(fc.constantFrom(...launchSpotIds), spotRecord, { minKeys: 1 }), (spots) => {
        const ids = Object.keys(spots);
        const decisions = decideStaticMapAssets(policyWith(spots), ids);

        assert.equal(decisions.length, ids.length, 'a spot was decided twice or dropped');
        for (const decision of decisions) {
          const record = spots[decision.spot_id]!;
          const citable = record.coordinate_attribution !== '' && record.orientation_attribution !== '';
          assert.equal(
            decision.kind === 'approved',
            citable,
            `${decision.spot_id} was ${decision.kind} with coordinate="${record.coordinate_attribution}" orientation="${record.orientation_attribution}"`,
          );
        }
      }),
    );
  });

  it('keeps one spot missing credit from changing any other spot decision', () => {
    fc.assert(
      fc.property(
        fc.dictionary(fc.constantFrom(...launchSpotIds), spotRecord, { minKeys: 2 }),
        fc.nat(),
        (spots, pick) => {
          const ids = Object.keys(spots);
          const victim = ids[pick % ids.length]!;
          const stripped = Object.fromEntries(
            Object.entries(spots).map(([id, record]) => (
              id === victim ? [id, { ...record, coordinate_attribution: '' }] : [id, record]
            )),
          );

          const before = decideStaticMapAssets(policyWith(spots), ids);
          const after = decideStaticMapAssets(policyWith(stripped), ids);

          const victimAfter = after.find((decision) => decision.spot_id === victim);
          assert.equal(victimAfter?.kind, 'refused', `${victim} kept its map with no location credit`);
          assert.deepEqual(
            after.filter((decision) => decision.spot_id !== victim),
            before.filter((decision) => decision.spot_id !== victim),
            `stripping ${victim} changed another spot's decision`,
          );
        },
      ),
    );
  });

  it('refuses a launch spot the policy never enumerated instead of inventing a record', () => {
    const decisions = decideStaticMapAssets(trackedPolicy, [...launchSpotIds, 'playa-que-no-existe']);
    const unknown = decisions.find((decision) => decision.spot_id === 'playa-que-no-existe');

    assert.equal(unknown?.kind, 'refused');
    assert.equal(unknown?.kind === 'refused' ? unknown.reason : '', 'absent_from_policy');
  });
});
